/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 * 
 * 
 * stripped because idk legality of distrubuting class-dumps. if only there was a way to find them on the internet...
 */




#import <UIKit/UIView.h>

@class NSMutableArray, SBIcon;

@interface SBIconList : UIView {
	
}

@end

